### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arjanvillon** [lurepheonix/hackintosh-asus-strix-z490-f#1]
Hi! Thanks for this amazing build.
I have the same hardware except for the RAM and brand of RX 580. Do you think it would work just directly using the OC or do I need to make some small changes for these parts? Thanks again.

**Comment by lurepheonix** [comment]
@arjanvillo hello!
Mostly, yes.
But note:
1. If you don't have the same case, you'll most likely need your own USB map. 
Also, I'm using a m2 network card, which is USB-mapped for BT.
Better do a one yourself anyway, it's explained in OC manual. Use [USBInjectAll](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#usb) as a substitute during set-up.
2. Enabling CSM is most likely not needed in your case, it's my GPU firmware that has UEFI broken (was re-flashed).
3. Update OpenCore and kexts, they're a bit outdated. My Z490-F broke, so I'm not supporting this repo anymore. Feel free to fork.
4. I don't provide serials for obvious reason.

**Comment by arjanvillon** [comment]
Thank you @lurepheonix! I'll do try to update this when I finish my build (because it's kind of hard to look for 10600k in my country).  Cheers!
